//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace Hangfire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.Dashboard.Content.resx.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t worry, continuations are working as expected. But your current job storage does not support some queries required to show this page. Please try to update your storage or wait until the full command set is implemented..
        /// </summary>
        public static string AwaitingJobsPage_ContinuationsWarning_Text {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_ContinuationsWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continuations are working, but this page can&apos;t be displayed.
        /// </summary>
        public static string AwaitingJobsPage_ContinuationsWarning_Title {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_ContinuationsWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No jobs found in awaiting state..
        /// </summary>
        public static string AwaitingJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string AwaitingJobsPage_Table_Options {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Table_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent.
        /// </summary>
        public static string AwaitingJobsPage_Table_Parent {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Table_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awaiting Jobs.
        /// </summary>
        public static string AwaitingJobsPage_Title {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not find the target method..
        /// </summary>
        public static string Common_CannotFindTargetMethod {
            get {
                return ResourceManager.GetString("Common_CannotFindTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Condition.
        /// </summary>
        public static string Common_Condition {
            get {
                return ResourceManager.GetString("Common_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continuations.
        /// </summary>
        public static string Common_Continuations {
            get {
                return ResourceManager.GetString("Common_Continuations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string Common_Created {
            get {
                return ResourceManager.GetString("Common_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to DELETE ALL selected jobs?.
        /// </summary>
        public static string Common_DeleteConfirm {
            get {
                return ResourceManager.GetString("Common_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected.
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting....
        /// </summary>
        public static string Common_Deleting {
            get {
                return ResourceManager.GetString("Common_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        public static string Common_Disabled {
            get {
                return ResourceManager.GetString("Common_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueue jobs.
        /// </summary>
        public static string Common_EnqueueButton_Text {
            get {
                return ResourceManager.GetString("Common_EnqueueButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueued.
        /// </summary>
        public static string Common_Enqueued {
            get {
                return ResourceManager.GetString("Common_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueueing....
        /// </summary>
        public static string Common_Enqueueing {
            get {
                return ResourceManager.GetString("Common_Enqueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetched.
        /// </summary>
        public static string Common_Fetched {
            get {
                return ResourceManager.GetString("Common_Fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job.
        /// </summary>
        public static string Common_Job {
            get {
                return ResourceManager.GetString("Common_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job expired..
        /// </summary>
        public static string Common_JobExpired {
            get {
                return ResourceManager.GetString("Common_JobExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job&apos;s state has been changed while fetching data..
        /// </summary>
        public static string Common_JobStateChanged_Text {
            get {
                return ResourceManager.GetString("Common_JobStateChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fewer details....
        /// </summary>
        public static string Common_LessDetails {
            get {
                return ResourceManager.GetString("Common_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More details....
        /// </summary>
        public static string Common_MoreDetails {
            get {
                return ResourceManager.GetString("Common_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No state.
        /// </summary>
        public static string Common_NoState {
            get {
                return ResourceManager.GetString("Common_NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day.
        /// </summary>
        public static string Common_PeriodDay {
            get {
                return ResourceManager.GetString("Common_PeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Week.
        /// </summary>
        public static string Common_PeriodWeek {
            get {
                return ResourceManager.GetString("Common_PeriodWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        public static string Common_Reason {
            get {
                return ResourceManager.GetString("Common_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requeue jobs.
        /// </summary>
        public static string Common_RequeueJobs {
            get {
                return ResourceManager.GetString("Common_RequeueJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server.
        /// </summary>
        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No deleted jobs found..
        /// </summary>
        public static string DeletedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("DeletedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted.
        /// </summary>
        public static string DeletedJobsPage_Table_Deleted {
            get {
                return ResourceManager.GetString("DeletedJobsPage_Table_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted Jobs.
        /// </summary>
        public static string DeletedJobsPage_Title {
            get {
                return ResourceManager.GetString("DeletedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The queue is empty..
        /// </summary>
        public static string EnqueuedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueued jobs.
        /// </summary>
        public static string EnqueuedJobsPage_Title {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;strong&gt;Failed jobs do not become expired&lt;/strong&gt; to allow you to re-queue them without any
        ///                time pressure. You should re-queue or delete them manually, or apply &lt;code&gt;AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete)&lt;/code&gt;
        ///                attribute to delete them automatically..
        /// </summary>
        public static string FailedJobsPage_FailedJobsNotExpire_Warning_Html {
            get {
                return ResourceManager.GetString("FailedJobsPage_FailedJobsNotExpire_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no failed jobs at the moment..
        /// </summary>
        public static string FailedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FailedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string FailedJobsPage_Table_Failed {
            get {
                return ResourceManager.GetString("FailedJobsPage_Table_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed Jobs.
        /// </summary>
        public static string FailedJobsPage_Title {
            get {
                return ResourceManager.GetString("FailedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The queue is empty..
        /// </summary>
        public static string FetchedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FetchedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetched jobs.
        /// </summary>
        public static string FetchedJobsPage_Title {
            get {
                return ResourceManager.GetString("FetchedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string HomePage_GraphHover_Failed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeeded.
        /// </summary>
        public static string HomePage_GraphHover_Succeeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History graph.
        /// </summary>
        public static string HomePage_HistoryGraph {
            get {
                return ResourceManager.GetString("HomePage_HistoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Realtime graph.
        /// </summary>
        public static string HomePage_RealtimeGraph {
            get {
                return ResourceManager.GetString("HomePage_RealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overview.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string JobDetailsPage_Created {
            get {
                return ResourceManager.GetString("JobDetailsPage_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete this job?.
        /// </summary>
        public static string JobDetailsPage_DeleteConfirm {
            get {
                return ResourceManager.GetString("JobDetailsPage_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;strong&gt;The job was aborted&lt;/strong&gt; – it is processed by server
        ///                        &lt;code&gt;{0}&lt;/code&gt; which is not in the 
        ///                        &lt;a href=&quot;{1}&quot;&gt;active servers&lt;/a&gt; list for now.
        ///                        It will be retried automatically after invisibility timeout, but you can
        ///                        also re-queue or delete it manually..
        /// </summary>
        public static string JobDetailsPage_JobAbortedNotActive_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobAbortedNotActive_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;strong&gt;Looks like the job was aborted&lt;/strong&gt; – it is processed by server
        ///                        &lt;code&gt;{0}&lt;/code&gt;, which reported its heartbeat more than 1 minute ago.
        ///                        It will be retried automatically after invisibility timeout, but you can
        ///                        also re-queue or delete it manually..
        /// </summary>
        public static string JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background job &apos;{0}&apos; has expired or could not be found on the server..
        /// </summary>
        public static string JobDetailsPage_JobExpired {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;strong&gt;The job is finished&lt;/strong&gt;.
        ///                    It will be removed automatically &lt;em&gt;&lt;abbr data-moment=&quot;{0}&quot;&gt;{1}&lt;/abbr&gt;&lt;/em&gt;..
        /// </summary>
        public static string JobDetailsPage_JobFinished_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobFinished_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job ID.
        /// </summary>
        public static string JobDetailsPage_JobId {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requeue.
        /// </summary>
        public static string JobDetailsPage_Requeue {
            get {
                return ResourceManager.GetString("JobDetailsPage_Requeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string JobDetailsPage_State {
            get {
                return ResourceManager.GetString("JobDetailsPage_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awaiting.
        /// </summary>
        public static string JobsSidebarMenu_Awaiting {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Awaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted.
        /// </summary>
        public static string JobsSidebarMenu_Deleted {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueued.
        /// </summary>
        public static string JobsSidebarMenu_Enqueued {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string JobsSidebarMenu_Failed {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing.
        /// </summary>
        public static string JobsSidebarMenu_Processing {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled.
        /// </summary>
        public static string JobsSidebarMenu_Scheduled {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeeded.
        /// </summary>
        public static string JobsSidebarMenu_Succeeded {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to site.
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated: {0}ms.
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time:.
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active Connections.
        /// </summary>
        public static string Metrics_ActiveConnections {
            get {
                return ResourceManager.GetString("Metrics_ActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awaiting.
        /// </summary>
        public static string Metrics_AwaitingCount {
            get {
                return ResourceManager.GetString("Metrics_AwaitingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted Jobs.
        /// </summary>
        public static string Metrics_DeletedJobs {
            get {
                return ResourceManager.GetString("Metrics_DeletedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueued.
        /// </summary>
        public static string Metrics_EnqueuedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueued / Queues.
        /// </summary>
        public static string Metrics_EnqueuedQueuesCount {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedQueuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} failed job(s) found. Retry or delete them manually..
        /// </summary>
        public static string Metrics_FailedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_FailedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed Jobs.
        /// </summary>
        public static string Metrics_FailedJobs {
            get {
                return ResourceManager.GetString("Metrics_FailedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing Jobs.
        /// </summary>
        public static string Metrics_ProcessingJobs {
            get {
                return ResourceManager.GetString("Metrics_ProcessingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recurring Jobs.
        /// </summary>
        public static string Metrics_RecurringJobs {
            get {
                return ResourceManager.GetString("Metrics_RecurringJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retries.
        /// </summary>
        public static string Metrics_Retries {
            get {
                return ResourceManager.GetString("Metrics_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled Jobs.
        /// </summary>
        public static string Metrics_ScheduledJobs {
            get {
                return ResourceManager.GetString("Metrics_ScheduledJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers.
        /// </summary>
        public static string Metrics_Servers {
            get {
                return ResourceManager.GetString("Metrics_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeeded Jobs.
        /// </summary>
        public static string Metrics_SucceededJobs {
            get {
                return ResourceManager.GetString("Metrics_SucceededJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Connections.
        /// </summary>
        public static string Metrics_TotalConnections {
            get {
                return ResourceManager.GetString("Metrics_TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jobs.
        /// </summary>
        public static string NavigationMenu_Jobs {
            get {
                return ResourceManager.GetString("NavigationMenu_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recurring Jobs.
        /// </summary>
        public static string NavigationMenu_RecurringJobs {
            get {
                return ResourceManager.GetString("NavigationMenu_RecurringJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retries.
        /// </summary>
        public static string NavigationMenu_Retries {
            get {
                return ResourceManager.GetString("NavigationMenu_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers.
        /// </summary>
        public static string NavigationMenu_Servers {
            get {
                return ResourceManager.GetString("NavigationMenu_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prev.
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total items.
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items per page.
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Looks like the job was aborted.
        /// </summary>
        public static string ProcessingJobsPage_Aborted {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No jobs are being processed right now..
        /// </summary>
        public static string ProcessingJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Started.
        /// </summary>
        public static string ProcessingJobsPage_Table_Started {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing Jobs.
        /// </summary>
        public static string ProcessingJobsPage_Title {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No jobs queued..
        /// </summary>
        public static string QueuesPage_NoJobs {
            get {
                return ResourceManager.GetString("QueuesPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No queued jobs found. Try to enqueue a job..
        /// </summary>
        public static string QueuesPage_NoQueues {
            get {
                return ResourceManager.GetString("QueuesPage_NoQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length.
        /// </summary>
        public static string QueuesPage_Table_Length {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next jobs.
        /// </summary>
        public static string QueuesPage_Table_NextsJobs {
            get {
                return ResourceManager.GetString("QueuesPage_Table_NextsJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queue.
        /// </summary>
        public static string QueuesPage_Table_Queue {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queues.
        /// </summary>
        public static string QueuesPage_Title {
            get {
                return ResourceManager.GetString("QueuesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceled.
        /// </summary>
        public static string RecurringJobsPage_Canceled {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable.
        /// </summary>
        public static string RecurringJobsPage_Disable {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        public static string RecurringJobsPage_Disabled {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabling....
        /// </summary>
        public static string RecurringJobsPage_Disabling {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable.
        /// </summary>
        public static string RecurringJobsPage_Enable {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabling....
        /// </summary>
        public static string RecurringJobsPage_Enabling {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No recurring jobs found..
        /// </summary>
        public static string RecurringJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("RecurringJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cron expression is invalid or don&apos;t have any occurrences over the next 100 years.
        /// </summary>
        public static string RecurringJobsPage_RecurringJobDisabled_Tooltip {
            get {
                return ResourceManager.GetString("RecurringJobsPage_RecurringJobDisabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cron.
        /// </summary>
        public static string RecurringJobsPage_Table_Cron {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last execution.
        /// </summary>
        public static string RecurringJobsPage_Table_LastExecution {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_LastExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next execution.
        /// </summary>
        public static string RecurringJobsPage_Table_NextExecution {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_NextExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time zone.
        /// </summary>
        public static string RecurringJobsPage_Table_TimeZone {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recurring jobs.
        /// </summary>
        public static string RecurringJobsPage_Title {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Triggering....
        /// </summary>
        public static string RecurringJobsPage_Triggering {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Triggering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trigger now.
        /// </summary>
        public static string RecurringJobsPage_TriggerNow {
            get {
                return ResourceManager.GetString("RecurringJobsPage_TriggerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All is OK – you have no retries..
        /// </summary>
        public static string RetriesPage_NoJobs {
            get {
                return ResourceManager.GetString("RetriesPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retries.
        /// </summary>
        public static string RetriesPage_Title {
            get {
                return ResourceManager.GetString("RetriesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h4&gt;Retries are working, but this page can&apos;t be displayed&lt;/h4&gt;
        ///        &lt;p&gt;
        ///            Don&apos;t worry, retries are working as expected. Your current job storage does not support
        ///            some queries required to show this page. Please try to update your storage or wait until
        ///            the full command set is implemented.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            Please go to the &lt;a href=&quot;{0}&quot;&gt;Scheduled jobs&lt;/a&gt; page to see all the
        ///            scheduled jobs including retries.
        ///        &lt;/p&gt;.
        /// </summary>
        public static string RetriesPage_Warning_Html {
            get {
                return ResourceManager.GetString("RetriesPage_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueue now.
        /// </summary>
        public static string ScheduledJobsPage_EnqueueNow {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_EnqueueNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no scheduled jobs..
        /// </summary>
        public static string ScheduledJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enqueue.
        /// </summary>
        public static string ScheduledJobsPage_Table_Enqueue {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Table_Enqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled.
        /// </summary>
        public static string ScheduledJobsPage_Table_Scheduled {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Table_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled Jobs.
        /// </summary>
        public static string ScheduledJobsPage_Title {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string ServersPage_Active {
            get {
                return ResourceManager.GetString("ServersPage_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no active servers. Background tasks will not be processed..
        /// </summary>
        public static string ServersPage_NoServers {
            get {
                return ResourceManager.GetString("ServersPage_NoServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some of the servers don&apos;t have heartbeat reported within the last minute and may be aborted. If they don&apos;t report heartbeat in the near future, they will be removed automatically after timeout is exceeded, no manual action is required.
        ///                    Incomplete background jobs running on those servers will be re-queued automatically, but you can speed up the process by checking the &lt;a href=&quot;{0}&quot;&gt;Processing Jobs&lt;/a&gt; page..
        /// </summary>
        public static string ServersPage_Note_Text {
            get {
                return ResourceManager.GetString("ServersPage_Note_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aborted servers will be removed automatically.
        /// </summary>
        public static string ServersPage_Note_Title {
            get {
                return ResourceManager.GetString("ServersPage_Note_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possibly aborted.
        /// </summary>
        public static string ServersPage_Possibly_Aborted {
            get {
                return ResourceManager.GetString("ServersPage_Possibly_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heartbeat.
        /// </summary>
        public static string ServersPage_Table_Heartbeat {
            get {
                return ResourceManager.GetString("ServersPage_Table_Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string ServersPage_Table_Name {
            get {
                return ResourceManager.GetString("ServersPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queues.
        /// </summary>
        public static string ServersPage_Table_Queues {
            get {
                return ResourceManager.GetString("ServersPage_Table_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Started.
        /// </summary>
        public static string ServersPage_Table_Started {
            get {
                return ResourceManager.GetString("ServersPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workers.
        /// </summary>
        public static string ServersPage_Table_Workers {
            get {
                return ResourceManager.GetString("ServersPage_Table_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers.
        /// </summary>
        public static string ServersPage_Title {
            get {
                return ResourceManager.GetString("ServersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No succeeded jobs found..
        /// </summary>
        public static string SucceededJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("SucceededJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeeded.
        /// </summary>
        public static string SucceededJobsPage_Table_Succeeded {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Table_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Duration.
        /// </summary>
        public static string SucceededJobsPage_Table_TotalDuration {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Table_TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeeded Jobs.
        /// </summary>
        public static string SucceededJobsPage_Title {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Title", resourceCulture);
            }
        }
    }
}
